export const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
};

export const PostsActionTypes = {
  SET_ALL_POSTS: "SET_ALL_POSTS",
  SET_USER_POSTS: "SET_USER_POSTS",
  DELETE_USER_PORT: "DELETE_USER_PORT",
  CREAT_USER_POST: "CREAT_USER_POST",
  SET_CURRENT_POST: "SET_CURRENT_POST",
};

export const CommentsActionTypes = {
  SET_CURRENT_COMMENTS: "SET_CURRENT_COMMENTS",
  DELETE_USER_COMMENT: "DELETE_USER_COMMENT",
  CREATE_USER_COMMENT: "CREATE_USER_COMMENT",
};
